
import React, { createContext, useState, useEffect, useContext, useCallback } from 'react';
import { AppState } from '../types';

// Define translations structure
type Translations = { [key: string]: string | Translations };

// Define translation files as any to avoid TypeScript errors with dynamic imports/requires
const en: Translations = {
  "sidebar": { "home": "Home", "search": "Search", "library": "Library", "settings": "Settings", "playlist": "Playlist" },
  "player": { "noSong": "No song selected", "shuffle": "Shuffle", "repeat": "Repeat: {{mode}}", "download": "Download song", "addToPlaylist": "Add to playlist", "newPlaylist": "New Playlist", "noPlaylists": "No playlists.", "favorite": "Favorite song", "showQueue": "Show queue", "unmute": "Unmute", "mute": "Mute", "partyMode": "Party Mode" },
  "home": { "goodMorning": "Good morning", "goodAfternoon": "Good afternoon", "goodEvening": "Good evening", "recommended": "Recommended For You", "newReleases": "New Releases From Your Artists" },
  "search": { "placeholder": "Search for songs, albums, artists...", "recent": "Recent Searches", "noResults": "No results found.", "noSongs": "No songs found for this query.", "noAlbums": "No albums found for this query.", "noArtists": "No artists found for this query.", "noPlaylists": "No playlists found for this query.", "prompt": "Search for your favorite music.", "promptSubtitle": "Results will appear here." },
  "library": { "all": "All", "playlists": "Playlists", "songs": "Songs", "artists": "Artists", "albums": "Albums", "newPlaylist": "New Playlist", "moreOptions": "More options", "delete": "Delete", "empty": "Your library is empty", "emptySubtitle": "Save songs, albums, and artists to see them here.", "recentPlaylists": "Recent Playlists", "recentAlbums": "Recent Albums", "recentArtists": "Recent Artists", "recentSongs": "Recent Songs", "deletePlaylistTitle": "Delete Playlist", "deletePlaylistConfirm": "Are you sure you want to permanently delete \"{{name}}\"?", "cancel": "Cancel", "myPlaylists": "My Playlists", "favoritePlaylists": "Favorite Playlists", "noFavPlaylists": "You haven't favorited any public playlists yet.", "sortBy": "Sort by: {{label}}", "sort_date_added": "Date Added", "sort_title_asc": "Title (A-Z)", "sort_title_desc": "Title (Z-A)", "noFavSongs": "You haven't favorited any songs yet.", "noFavArtists": "You haven't followed any artists yet.", "noFavAlbums": "You haven't favorited any albums yet." },
  "albumView": { "album": "Album", "songs": "{{count}} songs", "duration": "{{duration}} min", "removeFromFav": "Remove from favorites", "addToFav": "Add to favorites", "downloadAll": "Download all songs", "moreOptions": "More options", "addToQueue": "Add to Queue", "playShuffle": "Play Shuffle", "downloadM3U": "Download .m3u playlist", "downloadPreparing": "Preparing Download", "downloadFetching": "Fetching songs... ({{current}}/{{total}})", "downloadFetching_plural": "Fetching song {{current}} of {{total}}...", "downloadFailed": "Download Failed", "downloadFailedMsg": "Could not download any songs for this album.", "close": "Close", "downloadCompressing": "Compressing Files", "downloadCompressingMsg": "Creating your .zip file. This may take a moment...", "downloadCompressingProgress": "Compressing... {{percent}}%", "error": "Error", "errorZip": "Failed to create .zip file." },
  "playlistView": { "notFound": "Playlist not found. It may have been deleted.", "addSongsPrompt": "Add at least 3 songs to get recommendations.", "quickAddTitle": "Quick Add", "quickAddSearch": "Search for songs to add", "added": "Added", "add": "Add", "recommendations": "Recommended Songs", "recommendationsSubtitle": "Based on what's in this playlist.", "noRecs": "Could not fetch recommendations. The service might be temporarily unavailable.", "playlist": "Playlist", "deletePlaylistTitle": "Delete Playlist", "deletePlaylistConfirm": "Are you sure you want to delete \"{{name}}\"?", "cancel": "Cancel", "delete": "Delete", "editDetailsTitle": "Edit Details", "playlistName": "Nome da Playlist", "description": "Description (optional)", "save": "Save", "choosePhoto": "Choose Photo", "editDetails": "Edit details", "addSongs": "Add songs", "empty": "This playlist is empty.", "songCount": "{{count}} song", "songCount_plural": "{{count}} songs", "noResultsFor": "No results found for \"{{query}}\".", "sort_default": "Default", "sort_title": "Title", "sort_duration": "Duration" },
  "artistView": { "verified": "Verified Artist", "followers": "{{count}} followers", "following": "Following", "follow": "Follow", "popular": "Popular", "latestRelease": "Latest Release", "albums": "Albums", "about": "About", "readMore": "Read More", "showLess": "Show Less", "fansLike": "Fans Also Like" },
  "apiPlaylistView": { "publicPlaylist": "Public Playlist", "saveToLibrary": "Save to your library", "alreadySaved": "Already in your library", "favorite": "Favorite", "more": "More...", "addToQueue": "Add to Queue", "downloadZip": "Download .zip", "sortBy": "SORT BY", "sort_default": "Default", "sort_title": "Title", "sort_duration": "Duration", "title": "Title", "noSongs": "Could not find songs for this playlist.", "savedModalTitle": "Playlist Saved", "savedModalMsg": "\"{{name}}\" has been added to your library.", "close": "Close", "viewInLibrary": "View in Library" },
  "queue": { "party": "Party", "queue": "Queue", "host": "Host", "copyCode": "Copy Party Code", "copied": "Copied!", "online": "online", "sendReaction": "Send Reaction", "endParty": "End Party", "leaveParty": "Leave Party", "nowPlaying": "Now Playing", "upNext": "Up Next", "upNextAutoplay": "Up Next from Radio", "previouslyPlayed": "Previously Played", "empty": "Your Queue is Empty", "emptySubtitle": "Add some songs to get started!", "moveToTop": "Move to Top", "moveToBottom": "Move to Bottom", "removeFromQueue": "Remove from Queue", "autoplay": "Radio & Autoplay", "autoplaySubtitle": "We'll keep playing similar music when the queue ends." },
  "party": { "notFound": "Party not found.", "inactive": "This party seems to be inactive.", "joined": "Joined party!" },
  "songlist": { "noSongs": "No songs to display.", "menu": { "goToRadio": "Go to radio", "playNext": "Play Next", "addToQueue": "Add to Queue" } },
  "partyModal": { "joinTitle": "Join Party", "joinSubtitle": "Enter the 5-digit code to join.", "back": "Back", "joinButton": "Join Party", "joining": "Joining...", "createTitle": "Create a Party", "createSubtitle": "Set the rules for your listening party.", "collaborative": "Collaborative", "collaborativeDesc": "Everyone can add, remove, and reorder songs.", "djHost": "DJ Host", "djHostDesc": "Only you control the music queue.", "startButton": "Start Party", "shareTitle": "Party Started!", "shareSubtitle": "Share the code or link for friends to join.", "partyCode": "Party Code", "copyInvite": "Copy Invite Link", "linkCopied": "Link Copied!", "done": "Done", "landingTitle": "Party Mode", "landingSubtitle": "Listen to music together with friends, in real-time.", "createCardTitle": "Create a Party", "createCardDesc": "Be the host and invite your friends.", "joinCardTitle": "Join a Party", "joinCardDesc": "Got a code? Hop in here." },
  "settings": { "title": "Settings", "profile": { "title": "Your Profile", "description": "This is how you appear on MeMusic.", "changePhoto": "Change Photo", "editProfile": "Edit Profile", "cancel": "Cancel", "save": "Save", "chooseAvatar": "Choose Profile Picture", "random": "Random", "upload": "Upload" }, "language": { "title": "Language", "description": "Choose the display language for the app.", "english": "English", "portuguese": "Portuguese" }, "quality": { "title": "Audio Quality", "description": "Select the streaming quality. Higher quality uses more data.", "low": "Low", "lowDesc": "Uses less data.", "normal": "Normal", "normalDesc": "Balance of quality and data.", "high": "High", "highDesc": "Best audio quality." }, "data": { "title": "Manage Data", "description": "Back up your library to a file, or restore from a backup.", "import": "Import Library", "export": "Export Library", "importTitle": "Import Your Library", "importSubtitle": "Choose how to import from your backup file.", "merge": "Merge", "mergeDesc": "Add new items from the backup to your current library. No data will be deleted.", "replace": "Replace", "replaceDesc": "Warning: This will delete your current library before importing the backup.", "importSuccess": "Import Successful", "importFailure": "Import Failed", "importInvalidFormat": "Invalid data format: not an object.", "importReplaceSuccess": "Data replaced successfully.", "importMergeSuccess": "Data merged successfully.", "importParseError": "Failed to parse the file." }, "effects": { "title": "Audio Effects", "description": "Customize your listening with an equalizer, spatial audio, and reverb.", "enableEQ": "Enable Equalizer", "presets": "Presets", "reset": "Reset", "preset_flat": "Flat", "preset_pop": "Pop", "preset_rock": "Rock", "preset_jazz": "Jazz", "preset_voice": "Voice Booster", "enableReverb": "Enable Reverb", "intensity": "Intensity", "enable8D": "Enable 8D Audio", "eightDDesc": "Experience immersive sound that moves around you. Best with headphones." }, "about": { "title": "About MeMusic", "description": "Information about the project and its technologies.", "version": "Version", "p1": "This music player is a personal project designed to demonstrate modern web technologies and provide a fluid, account-free music listening experience.", "p2": "All music data is sourced from the unofficial", "p3": "All rights to the music belong to their respective owners.", "sourceCode": "Source Code & Credits", "tech": "Technologies Used" } },
  "modals": { "partyEnded": { "title": "Party Ended", "ok": "OK", "endedByHost": "The party \"{{partyId}}\" was ended by the host.", "connectionLost": "Connection to the host of party \"{{partyId}}\" was lost.", "ended": "The party \"{{partyId}}\" has ended." }, "createPlaylist": { "title": "Create New Playlist", "confirm": "Create", "cancel": "Cancel", "namePlaceholder": "Playlist Name", "descPlaceholder": "Add an optional description" } }
};
const pt: Translations = {
  "sidebar": { "home": "Início", "search": "Pesquisar", "library": "Biblioteca", "settings": "Definições", "playlist": "Playlist" },
  "player": { "noSong": "Nenhuma música selecionada", "shuffle": "Aleatório", "repeat": "Repetir: {{mode}}", "download": "Baixar música", "addToPlaylist": "Adicionar à playlist", "newPlaylist": "Nova Playlist", "noPlaylists": "Nenhuma playlist.", "favorite": "Música favorita", "showQueue": "Mostrar fila", "unmute": "Ativar som", "mute": "Silenciar", "partyMode": "Modo Festa" },
  "home": { "goodMorning": "Bom dia", "goodAfternoon": "Boa tarde", "goodEvening": "Boa noite", "recommended": "Recomendado Para Você", "newReleases": "Novos Lançamentos Dos Seus Artistas" },
  "search": { "placeholder": "Procure por músicas, álbuns, artistas...", "recent": "Pesquisas Recentes", "noResults": "Nenhum resultado encontrado.", "noSongs": "Nenhuma música encontrada para esta pesquisa.", "noAlbums": "Nenhum álbum encontrado para esta pesquisa.", "noArtists": "Nenhum artista encontrado para esta pesquisa.", "noPlaylists": "Nenhuma playlist encontrada para esta pesquisa.", "prompt": "Procure pela sua música favorita.", "promptSubtitle": "Os resultados aparecerão aqui." },
  "library": { "all": "Tudo", "playlists": "Playlists", "songs": "Músicas", "artists": "Artistas", "albums": "Álbuns", "newPlaylist": "Nova Playlist", "moreOptions": "Mais opções", "delete": "Apagar", "empty": "A sua biblioteca está vazia", "emptySubtitle": "Guarde músicas, álbuns e artistas para os ver aqui.", "recentPlaylists": "Playlists Recentes", "recentAlbums": "Álbuns Recentes", "recentArtists": "Artistas Recentes", "recentSongs": "Músicas Recentes", "deletePlaylistTitle": "Apagar Playlist", "deletePlaylistConfirm": "Tem a certeza que quer apagar permanentemente \"{{name}}\"?", "cancel": "Cancelar", "myPlaylists": "As Minhas Playlists", "favoritePlaylists": "Playlists Favoritas", "noFavPlaylists": "Ainda não favoritou nenhuma playlist pública.", "sortBy": "Ordenar por: {{label}}", "sort_date_added": "Data de Adição", "sort_title_asc": "Título (A-Z)", "sort_title_desc": "Título (Z-A)", "noFavSongs": "Ainda não favoritou nenhuma música.", "noFavArtists": "Ainda não seguiu nenhum artista.", "noFavAlbums": "Ainda não favoritou nenhum álbum." },
  "albumView": { "album": "Álbum", "songs": "{{count}} músicas", "duration": "{{duration}} min", "removeFromFav": "Remover dos favoritos", "addToFav": "Adicionar aos favoritos", "downloadAll": "Baixar todas as músicas", "moreOptions": "Mais opções", "addToQueue": "Adicionar à Fila", "playShuffle": "Tocar em Aleatório", "downloadM3U": "Baixar playlist .m3u", "downloadPreparing": "A Preparar o Download", "downloadFetching": "A obter músicas... ({{current}}/{{total}})", "downloadFetching_plural": "A obter música {{current}} de {{total}}...", "downloadFailed": "Falha no Download", "downloadFailedMsg": "Não foi possível baixar nenhuma música para este álbum.", "close": "Fechar", "downloadCompressing": "A Comprimir Ficheiros", "downloadCompressingMsg": "A criar o seu ficheiro .zip. Isto pode demorar um momento...", "downloadCompressingProgress": "A comprimir... {{percent}}%", "error": "Erro", "errorZip": "Falha ao criar o ficheiro .zip." },
  "playlistView": { "notFound": "Playlist não encontrada. Pode ter sido apagada.", "addSongsPrompt": "Adicione pelo menos 3 músicas para obter recomendações.", "quickAddTitle": "Adição Rápida", "quickAddSearch": "Procure por músicas para adicionar", "added": "Adicionado", "add": "Adicionar", "recommendations": "Músicas Recomendadas", "recommendationsSubtitle": "Com base no que está nesta playlist.", "noRecs": "Não foi possível obter recomendações. O serviço pode estar temporariamente indisponível.", "playlist": "Playlist", "deletePlaylistTitle": "Apagar Playlist", "deletePlaylistConfirm": "Tem a certeza que quer apagar \"{{name}}\"?", "cancel": "Cancelar", "delete": "Apagar", "editDetailsTitle": "Editar Detalhes", "playlistName": "Nome da Playlist", "description": "Descrição (opcional)", "save": "Guardar", "choosePhoto": "Escolher Foto", "editDetails": "Editar detalhes", "addSongs": "Adicionar músicas", "empty": "Esta playlist está vazia.", "songCount": "{{count}} música", "songCount_plural": "{{count}} músicas", "noResultsFor": "Nenhum resultado encontrado para \"{{query}}\".", "sort_default": "Padrão", "sort_title": "Título", "sort_duration": "Duração" },
  "artistView": { "verified": "Artista Verificado", "followers": "{{count}} seguidores", "following": "A Seguir", "follow": "Seguir", "popular": "Popular", "latestRelease": "Último Lançamento", "albums": "Álbuns", "about": "Sobre", "readMore": "Ler Mais", "showLess": "Mostrar Menos", "fansLike": "Os Fãs Também Gostam" },
  "apiPlaylistView": { "publicPlaylist": "Playlist Pública", "saveToLibrary": "Guardar na sua biblioteca", "alreadySaved": "Já na sua biblioteca", "favorite": "Favorito", "more": "Mais...", "addToQueue": "Adicionar à Fila", "downloadZip": "Baixar .zip", "sortBy": "ORDENAR POR", "sort_default": "Padrão", "sort_title": "Título", "sort_duration": "Duração", "title": "Título", "noSongs": "Não foi possível encontrar músicas para esta playlist.", "savedModalTitle": "Playlist Guardada", "savedModalMsg": "\"{{name}}\" foi adicionada à sua biblioteca.", "close": "Fechar", "viewInLibrary": "Ver na Biblioteca" },
  "queue": { "party": "Festa", "queue": "Fila", "host": "Anfitrião", "copyCode": "Copiar Código da Festa", "copied": "Copiado!", "online": "online", "sendReaction": "Enviar Reação", "endParty": "Terminar Festa", "leaveParty": "Sair da Festa", "nowPlaying": "A Tocar Agora", "upNext": "A Seguir", "upNextAutoplay": "A Seguir na Rádio", "previouslyPlayed": "Tocadas Anteriormente", "empty": "A Sua Fila Está Vazia", "emptySubtitle": "Adicione algumas músicas para começar!", "moveToTop": "Mover para o Topo", "moveToBottom": "Mover para o Fim", "removeFromQueue": "Remover da Fila", "autoplay": "Rádio & Autoplay", "autoplaySubtitle": "A música continuará a tocar automaticamente." },
   "party": { "notFound": "Festa não encontrada.", "inactive": "Esta festa parece estar inativa.", "joined": "Entrou na festa!" },
  "songlist": { "noSongs": "Nenhuma música para exibir.", "menu": { "goToRadio": "Ir para a rádio", "playNext": "Tocar a Seguir", "addToQueue": "Adicionar à Fila" } },
  "partyModal": { "joinTitle": "Entrar na Festa", "joinSubtitle": "Insira o código de 5 dígitos para participar.", "back": "Voltar", "joinButton": "Entrar na Festa", "joining": "A Entrar...", "createTitle": "Criar uma Festa", "createSubtitle": "Defina as regras para a sua festa de audição.", "collaborative": "Colaborativo", "collaborativeDesc": "Todos podem adicionar, remover e reordenar músicas.", "djHost": "Anfitrião é o DJ", "djHostDesc": "Apenas você pode controlar a fila de músicas.", "startButton": "Começar Festa", "shareTitle": "A Festa Começou!", "shareSubtitle": "Partilhe o código ou link para os seus amigos entrarem.", "partyCode": "Código da Festa", "copyInvite": "Copiar Link de Convite", "linkCopied": "Link Copiado!", "done": "Concluído", "landingTitle": "Modo Festa", "landingSubtitle": "Ouça música em conjunto com amigos, em tempo real.", "createCardTitle": "Criar uma Festa", "createCardDesc": "Seja o anfitrião e convide os seus amigos.", "joinCardTitle": "Entrar numa Festa", "joinCardDesc": "Tem um código? Entre aqui." },
  "settings": { "title": "Definições", "profile": { "title": "O Seu Perfil", "description": "É assim que você aparece no MeMusic.", "changePhoto": "Mudar foto", "editProfile": "Editar Perfil", "cancel": "Cancelar", "save": "Guardar", "chooseAvatar": "Escolha a Foto de Perfil", "random": "Aleatório", "upload": "Carregar" }, "language": { "title": "Idioma", "description": "Escolha o idioma de exibição para a aplicação.", "english": "Inglês", "portuguese": "Português" }, "quality": { "title": "Qualidade do Áudio", "description": "Selecione a qualidade do streaming. Uma qualidade superior utiliza mais dados.", "low": "Baixa", "lowDesc": "Usa menos dados.", "normal": "Normal", "normalDesc": "Equilíbrio entre qualidade e dados.", "high": "Alta", "highDesc": "Melhor qualidade de áudio." }, "data": { "title": "Gerenciar Dados", "description": "Faça o backup da sua biblioteca para um ficheiro ou restaure-a a partir de um backup.", "import": "Importar Biblioteca", "export": "Exportar Biblioteca", "importTitle": "Importar a Sua Biblioteca", "importSubtitle": "Escolha como importar do seu ficheiro de backup.", "merge": "Juntar", "mergeDesc": "Adicionar novos itens do backup à sua biblioteca atual. Nenhum dado será apagado.", "replace": "Substituir", "replaceDesc": "Aviso: Isto irá apagar a sua biblioteca atual antes de importar o backup.", "importSuccess": "Importação bem-sucedida", "importFailure": "Falha na importação", "importInvalidFormat": "Formato de dados inválido: não é um objeto.", "importReplaceSuccess": "Dados substituídos com sucesso.", "importMergeSuccess": "Dados mesclados com sucesso.", "importParseError": "Falha ao analisar o ficheiro." }, "effects": { "title": "Efeitos de Áudio", "description": "Personalize a sua experiência de audição com equalizador, áudio espacial e reverberação.", "enableEQ": "Ativar Equalizador", "presets": "Predefinições", "reset": "Repor", "preset_flat": "Plano", "preset_pop": "Pop", "preset_rock": "Rock", "preset_jazz": "Jazz", "preset_voice": "Amplificador de Voz", "enableReverb": "Ativar Reverberação", "intensity": "Intensidade", "enable8D": "Ativar Áudio 8D", "eightDDesc": "Experimente um som imersivo que se move à sua volta. Melhor com auscultadores." }, "about": { "title": "Sobre o MeMusic", "description": "Informações sobre o projeto e as suas tecnologias.", "version": "Versão", "p1": "Este leitor de música é um projeto pessoal concebido para demonstrar tecnologias web modernas e proporcionar uma experiência de audição de música fluida e sem necessidade de conta.", "p2": "Todos os dados musicais são obtidos a partir da API não oficial", "p3": "Todos os direitos sobre a música pertencem aos seus respetivos proprietários.", "sourceCode": "Código Fonte e Créditos", "tech": "Tecnologias utilizadas" } },
  "modals": { "partyEnded": { "title": "Festa Terminada", "ok": "OK", "endedByHost": "A festa \"{{partyId}}\" foi terminada pelo anfitrião.", "connectionLost": "A ligação ao anfitrião da festa \"{{partyId}}\" foi perdida.", "ended": "A festa \"{{partyId}}\" terminou." }, "createPlaylist": { "title": "Criar Nova Playlist", "confirm": "Criar", "cancel": "Cancelar", "namePlaceholder": "Nome da Playlist", "descPlaceholder": "Adicionar uma descrição opcional" } }
};

const translations = { en, pt };

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: { [key: string]: string | number }) => string;
}

export const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

const resolveKey = (obj: Translations, key: string): string => {
  const result = key.split('.').reduce((acc, part) => {
    if (acc && typeof acc === 'object' && !Array.isArray(acc) && part in acc) {
      return (acc as Translations)[part];
    }
    return undefined;
  }, obj);
  if (typeof result !== 'string') {
    const fallbackResult = key.split('.').reduce((acc, part) => {
        if (acc && typeof acc === 'object' && !Array.isArray(acc) && part in acc) return (acc as Translations)[part];
        return undefined;
    }, translations.en);
     return typeof fallbackResult === 'string' ? fallbackResult : key;
  }
  return result;
};

interface LanguageProviderProps {
    children: React.ReactNode;
    language: Language;
    setAppState: (updater: (draft: AppState) => void) => void;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children, language, setAppState }) => {
  const [currentTranslations, setCurrentTranslations] = useState<Translations>(translations[language]);

  useEffect(() => {
    setCurrentTranslations(translations[language]);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setAppState(draft => {
        draft.settings.language = lang;
    });
  }

  const t = useCallback((key: string, replacements?: { [key: string]: string | number }): string => {
    let translation = resolveKey(currentTranslations, key);
    if (replacements) {
        Object.keys(replacements).forEach(rKey => {
            translation = translation.replace(`{{${rKey}}}`, String(replacements[rKey]));
        });
    }
    return translation;
  }, [currentTranslations]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
